### ISSUE TITLE
Error when construct the disease network

### ISSUE THREAD

**Issue by huijianpzh** [X-DataInitiative/tick#144]
Hi,
 When I want to build the disease network, I met a mistake.
 I have 291 kinds of diseases totally.
 However, nobody will have all the diseases.
 So there may be some [ ] in the events.
 And the tick can not handle this situation. (I used inference.HawkesExpKern)
What should I do?
 Is it possible for Tick to solve the problem?
Thanks,

**Comment by Dekken** [comment]
can you provide a stack trace or minimal example?

**Comment by huijianpzh** [comment]
Traceback (most recent call last):
  File "hawkes.py", line 115, in <module>
    learner.fit(hawkes_events)
  File "/home/huijian/.conda/envs/py3/lib/python3.6/site-packages/tick/inference/base/learner_hawkes_param.py", line 165, in fit
    model_obj.fit(events)
  File "/home/huijian/.conda/envs/py3/lib/python3.6/site-packages/tick/optim/model/base/model_hawkes.py", line 70, in fit
    return ModelFirstOrder.fit(self, data)
  File "/home/huijian/.conda/envs/py3/lib/python3.6/site-packages/tick/optim/model/base/model_first_order.py", line 60, in fit
    Model.fit(self, *args)
  File "/home/huijian/.conda/envs/py3/lib/python3.6/site-packages/tick/optim/model/base/model.py", line 77, in fit
    self._set_data(*args)
  File "/home/huijian/.conda/envs/py3/lib/python3.6/site-packages/tick/optim/model/hawkes_fixed_expkern_leastsq.py", line 117, in _set_data
    ModelHawkes._set_data(self, events)
  File "/home/huijian/.conda/envs/py3/lib/python3.6/site-packages/tick/optim/model/base/model_hawkes.py", line 91, in _set_data
    end_times = np.array([max(map(max, e)) for e in events])
  File "/home/huijian/.conda/envs/py3/lib/python3.6/site-packages/tick/optim/model/base/model_hawkes.py", line 91, in <listcomp>
    end_times = np.array([max(map(max, e)) for e in events])
ValueError: max() arg is an empty sequence

**Comment by huijianpzh** [comment]
Actually, I may know what happens. But in my case, an event may have 291 dimensions. But some dimensions may be empty for the patient may not have that disease. I intend to set these dimensions to be "[ ]"
I coded it like following:
p_time_stamps.append(np.array([],dtype=np.double)).

I want to know how to deal with it, if I have some dimensions are empty.
Like that events[j] = []

**Comment by huijianpzh** [comment]
The record of every patient can be seen as a time series.
Then it has d dimensions (The num of the diseases)
And the data looks like:
[disease1] [time1, time2, ... timen]
[disease2] []
[disease3] [time1, time2,... timem]
[disease4] ....

I do not know how to deal with disease2 when programming with tick.

**Comment by Mbompr** [comment]
Hi, did you download tick with pip or did you install it from source? Lately, we have merged a new pull request to allow empty components in a list of realization (#111). It could be the same problem you are encountering. 
The version on pip does not contain this feature yet, so you might have to build tick from source.

**Comment by huijianpzh** [comment]
I download tick with pip. I will try it right away.

**Comment by huijianpzh** [comment]
hi, 
I have tried on two machines building the tick from source on Linux.
They both report that:

>>> import tick
Traceback (most recent call last):
  File "/home/software/tick/tick/array/build/array.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_array', [dirname(__file__)])
  File "/root/anaconda2/envs/tick/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_array'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/software/tick/tick/__init__.py", line 3, in <module>
    import tick.base
  File "/home/software/tick/tick/base/__init__.py", line 21, in <module>
    from tick.array import *
  File "/home/software/tick/tick/array/__init__.py", line 3, in <module>
    from .build import array
  File "/home/software/tick/tick/array/build/array.py", line 28, in <module>
    _array = swig_import_helper()
  File "/home/software/tick/tick/array/build/array.py", line 20, in swig_import_helper
    import _array
ModuleNotFoundError: No module named '_array'

I do not know the module _array. And I use Anaconda Enviroment.
Thanks,

**Comment by stephanegaiffas** [comment]
Hi, have you compiled the library ? Please have a lot for instructions in the readme, it’s pretty easy.
Best regards

Envoyé de mon iPhone

**Comment by Mbompr** [comment]
Indeed, did you follow this method? https://github.com/X-DataInitiative/tick/blob/master/INSTALL.md#manual-install---linux--osx

If so, please check that the Python executable you have used for `python setup.py build install` is the same Python as the one you use to run your script. Btw, did you add the Python generated module to your PYTHONPATH?
