### ISSUE TITLE
Weird unittest failing  since last release of Mac OS

### ISSUE THREAD

**Issue by stephanegaiffas** [X-DataInitiative/tick#165]
Here is the log :

======================================================================
ERROR: tick.survival.build.array_test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tick.survival.build.array_test
Traceback (most recent call last):
  File "/Users/stephane.gaiffas/Code/tick/tick/survival/build/array_test.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/Users/stephane.gaiffas/anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'tick.survival.build._array_test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stephane.gaiffas/anaconda/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/stephane.gaiffas/anaconda/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/stephane.gaiffas/Code/tick/tick/survival/build/array_test.py", line 17, in <module>
    _array_test = swig_import_helper()
  File "/Users/stephane.gaiffas/Code/tick/tick/survival/build/array_test.py", line 16, in swig_import_helper
    return importlib.import_module('_array_test')
  File "/Users/stephane.gaiffas/anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_array_test'

**Comment by Dekken** [comment]
How was this caused?

Was this build from source or from pip?

can you provide commands please?

it looks like a build mixup - there is no "_array_test"

**Comment by Dekken** [comment]
is this reproducable? I haven't seen it on travis or any builds on my mac
 
@Mbompr  what do you think?

**Comment by Mbompr** [comment]
It doesn't occur on my mac either... I'm on OSX 10.12 though
