### ISSUE TITLE
numpydoc docsrape error when importing tick 

### ISSUE THREAD

**Issue by mloning** [X-DataInitiative/tick#262]
I'm not able to import `tick`, not sure what I'm doing wrong, I followed the setup instructions.

Running `python3 -c "import tick;"` from your setup instructions gives me the following error: 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ucfamml/.conda/envs/point_processes/lib/python3.6/site-packages/tick/__init__.py", line 3, in <module>
    import tick.base
  File "/home/ucfamml/.conda/envs/point_processes/lib/python3.6/site-packages/tick/base/__init__.py", line 23, in <module>
    from .timefunc import TimeFunction
  File "/home/ucfamml/.conda/envs/point_processes/lib/python3.6/site-packages/tick/base/timefunc.py", line 5, in <module>
    from tick.base.base import Base
  File "/home/ucfamml/.conda/envs/point_processes/lib/python3.6/site-packages/tick/base/base.py", line 482, in <module>
    class Base(metaclass=BaseMeta):
  File "/home/ucfamml/.conda/envs/point_processes/lib/python3.6/site-packages/tick/base/base.py", line 416, in __new__
    classinfos[cls_key]['attr'] = extract_attrinfos(class_name, attrs)
  File "/home/ucfamml/.conda/envs/point_processes/lib/python3.6/site-packages/tick/base/base.py", line 295, in extract_attrinfos
    BaseMeta.find_documented_attributes(class_name, attrs):
  File "/home/ucfamml/.conda/envs/point_processes/lib/python3.6/site-packages/tick/base/base.py", line 251, in find_documented_attributes
    parsed_doc = nd.docscrape.ClassDoc(None, doc=current_class_doc)
AttributeError: module 'numpydoc' has no attribute 'docscrape'
```

This is my conda environment: 
```
alabaster                 0.7.11                    <pip>
Babel                     2.6.0                     <pip>
blas                      1.1                    openblas    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
chardet                   3.0.4                     <pip>
cycler                    0.10.0                    <pip>
docutils                  0.14                      <pip>
idna                      2.7                       <pip>
imagesize                 1.0.0                     <pip>
Jinja2                    2.10                      <pip>
kiwisolver                1.0.1                     <pip>
libgcc-ng                 7.2.0                hdf63c60_3    anaconda
libgfortran               3.0.0                         1
libgfortran-ng            7.2.0                hdf63c60_3    anaconda
libstdcxx-ng              7.2.0                hdf63c60_3    anaconda
MarkupSafe                1.0                       <pip>
matplotlib                2.2.2                     <pip>
ncurses                   5.9                          10    conda-forge
numpy                     1.14.5          py36_blas_openblashd3ea46f_200  [blas_openblas]  conda-forge
numpy                     1.14.5                    <pip>
numpydoc                  0.8.0                     <pip>
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2o                        0    conda-forge
packaging                 17.1                      <pip>
pandas                    0.23.1                    <pip>
pip                       10.0.1                    <pip>
pip                       9.0.3                    py36_0    conda-forge
Pygments                  2.2.0                     <pip>
pyparsing                 2.2.0                     <pip>
python                    3.6.5                         1    conda-forge
python-dateutil           2.7.3                     <pip>
pytz                      2018.4                    <pip>
readline                  7.0                           0    conda-forge
requests                  2.19.1                    <pip>
scikit-learn              0.19.1                    <pip>
scipy                     1.1.0                     <pip>
setuptools                39.2.0                   py36_0    conda-forge
six                       1.11.0                    <pip>
snowballstemmer           1.2.1                     <pip>
Sphinx                    1.7.5                     <pip>
sphinxcontrib-websupport  1.1.0                     <pip>
sqlite                    3.20.1                        2    conda-forge
tick                      0.4.0.0                   <pip>
tk                        8.6.7                         0    conda-forge
urllib3                   1.23                      <pip>
wheel                     0.31.0                   py36_0    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

**Comment by stephanegaiffas** [comment]
Hey, it seems to be the same as #236, have you installed from pip on from source ? Installing from source might solve the problem.
Cheers

**Comment by mloning** [comment]
When trying to install from source, I get his problem. Not sure if it's related though. Any idea how to solve it? Thanks! 
```
running build
running build_ext
building 'tick.array.build._array' extension
swigging lib/swig/array/array_module.i to lib/swig/array/array_module_wrap.cpp
swig -python -py3 -c++ -modern -new_repr -Ilib/swig/base -Ilib/include -outdir tick/array/build -Isrc/swig/array -DDEBUG_COSTLY_THROW -o lib/swig/array/array_module_wrap.cpp lib/swig/array/array_module.i
C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

compile options: '-DHAVE_CBLAS -DTICK_CBLAS_AVAILABLE -Iinclude -Ilib/third_party/cereal/include -I/home/ucfamml/.conda/envs/point_processes/lib/python3.6/site-packages/numpy/core/include -I/home/ucfamml/.conda/envs/point_processes/include/python3.6m -c'
extra options: '-D_FILE_OFFSET_BITS=64 -DPYTHON_LINK -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -Ilib/include -DTICK_SPARSE_INDICES_INT32 -std=c++11 -O2 -ffast-math -Wall -Werror -Wno-uninitialized -Isrc/swig/array -DDEBUG_COSTLY_THROW'
gcc: lib/swig/array/array_module_wrap.cpp
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from lib/include/tick/array/abstractarray1d2d.h:21:0,
                 from lib/include/tick/array/basearray.h:6,
                 from lib/include/tick/array/array.h:16,
                 from lib/include/tick/array/carray_python.h:12,
                 from lib/swig/array/array_module_wrap.cpp:3133:
lib/include/tick/array/vector_operations.h:101:19: fatal error: cblas.h: No such file or directory
 #include <cblas.h>
                   ^
compilation terminated.
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from lib/include/tick/array/abstractarray1d2d.h:21:0,
                 from lib/include/tick/array/basearray.h:6,
                 from lib/include/tick/array/array.h:16,
                 from lib/include/tick/array/carray_python.h:12,
                 from lib/swig/array/array_module_wrap.cpp:3133:
lib/include/tick/array/vector_operations.h:101:19: fatal error: cblas.h: No such file or directory
 #include <cblas.h>
                   ^
compilation terminated.
error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_CBLAS -DTICK_CBLAS_AVAILABLE -Iinclude -Ilib/third_party/cereal/include -I/home/ucfamml/.conda/envs/point_processes/lib/python3.6/site-packages/numpy/core/include -I/home/ucfamml/.conda/envs/point_processes/include/python3.6m -c lib/swig/array/array_module_wrap.cpp -o build/temp.linux-x86_64-3.6/lib/swig/array/array_module_wrap.o -D_FILE_OFFSET_BITS=64 -DPYTHON_LINK -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -Ilib/include -DTICK_SPARSE_INDICES_INT32 -std=c++11 -O2 -ffast-math -Wall -Werror -Wno-uninitialized -Isrc/swig/array -DDEBUG_COSTLY_THROW" failed with exit status 1
```

**Comment by Dekken** [comment]
if you try building with the following command I think it should work

```
python3 setup.py build_ext --inplace bdist_wheel
```

**Comment by mloning** [comment]
Thank you, so this has worked now! Once it's built, is there any proper way to install the files into a preferred environment? It did not install automatically into the active conda env and is not showing up when `conda list -n point_processes`. I've now copied them into a `.../site-packages/tick/` folder and I can import it when in Python.

**Comment by Dekken** [comment]
The previous command should have given you a directory "dist" which contained a whl file which you could pip install

**Comment by mloning** [comment]
Okay, makes sense, thanks! That solved my issue.
