### ISSUE TITLE
issue with tick array module after installation

### ISSUE THREAD

**Issue by equivarius** [X-DataInitiative/tick#469]
Trying to install tick on Ubuntu 18.04, but ending up with an error about the tick array module:

` ImportError: cannot import name '_array' from 'tick.array.build'`

This happens after otherwise successful installation, even with the simplest test, e.g.

`python -c "import tick;"`

I've tried installing with `pip`, or compiling from source, but the result is just the same. The full error trace looks like this (the installation directory path has been truncated to <path_to_tick>):

` python -c "import tick;"`
`Traceback (most recent call last):`
 ` File "<string>", line 1, in <module>`
 ` File "<path_to_tick>/tick/tick/__init__.py", line 6, in <module>  import tick.base`
  `File "<path_to_tick>/tick/tick/base/__init__.py", line 23, in <module>
    from tick.array import *`
  `File "<path_to_tick>/tick/tick/array/__init__.py", line 3, in <module>
    from .build import array`
 ` File "<path_to_tick>/tick/tick/array/build/array.py", line 13, in <module>
    from . import _array`
`ImportError: cannot import name '_array' from 'tick.array.build' (<path_to_tick>/tick/tick/array/build/__init__.py)`

Running Python 3.6 with all the tick prerequisites installed.

**Comment by RunKZhang** [comment]
I met the same problem. How did you handle it?

**Comment by Wambyat** [comment]
Hey did this get solved? I have the same error.

**Comment by PhilipDeegan** [comment]
this should be resolved

**Comment by Wambyat** [comment]
Ahhh damn alright. Thanks for the reply. Best wishes.
