### ISSUE TITLE
Tick doesn't run in Colab anymore

### ISSUE THREAD

**Issue by lexmar07** [X-DataInitiative/tick#517]
After the update of Colab for Python 3.10, I can't find a way to run Tick 

1. `!pip install tick`

results 

  
> error: subprocess-exited-with-error
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

2. An attempt to install it from scratch with Python 3.7 installed with a clean setup with TICK_ERROR = 1

`!source Env0/bin/activate;  cd tick ; sudo sh/clean_build_test.sh`

give errors:

>  ‘y’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  180 |       (*sampled_y_primitive)[i] = (*sampled_y_primitive)[i - 1] + y * dt;

3. Launch without TICK_ERROR = 0 brings 

> tick (unittest.loader._FailedTest) ... ERROR
ERROR: tick (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tick
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/content/tick/tick/__init__.py", line 6, in <module>
    import tick.base
  File "/content/tick/tick/base/__init__.py", line 21, in <module>
    _set_mpl_backend()
  File "/content/tick/tick/base/__init__.py", line 10, in _set_mpl_backend
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'

although matplotlib is of course installed, e.g, 
`!source Env0/bin/activate; pip freeze
`

> alabaster==0.7.13
Babel==2.12.1
certifi==2023.5.7
charset-normalizer==3.2.0
cycler==0.11.0
dill==0.3.6
docutils==0.19
fonttools==4.38.0
idna==3.4
imagesize==1.4.1
importlib-metadata==6.7.0
Jinja2==3.1.2
joblib==1.3.1
kiwisolver==1.4.4
MarkupSafe==2.1.3
matplotlib==3.5.3
numpy==1.21.6
numpydoc==1.5.0
packaging==23.1
pandas==1.3.5
Pillow==9.5.0
Pygments==2.15.1
pyparsing==3.1.0
python-dateutil==2.8.2
pytz==2023.3
requests==2.31.0
scikit-learn==1.0.2
scipy==1.7.3
six==1.16.0
snowballstemmer==2.2.0
Sphinx==5.3.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
threadpoolctl==3.1.0
typing_extensions==4.7.1
urllib3==2.0.3
zipp==3.15.0

**Comment by RichardShea** [comment]
Same here...Any update?

Thank you,

-Richard

**Comment by ranabirbasu12** [comment]
Same here. Any progress on its resolution?

Thanks!
